package(default_visibility = ["//closure:__subpackages__"])

load("//closure/compiler:closure_js_library.bzl", "closure_js_library")

closure_js_library(
    name = "phantom_lib",
    externs = ["phantom.js"],
    language = "ECMASCRIPT5_STRICT",
)
